# Generated by Django 5.2.17 on 2026-08-11 17:54

import pages.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='✓', max_length=8, verbose_name='Ikon (emoji)')),
                ('title', models.CharField(max_length=120, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=120, verbose_name='Sarlavha (ru)')),
                ('text', models.TextField(verbose_name='Matn')),
                ('text_ru', models.TextField(blank=True, verbose_name='Matn (ru)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Afzallik',
                'verbose_name_plural': 'Afzalliklar',
                'ordering': ['sort_order', 'id'],
            },
            bases=(pages.mixins.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (ru)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='Qisqacha')),
                ('excerpt_ru', models.CharField(blank=True, max_length=300, verbose_name='Qisqacha (ru)')),
                ('body', models.TextField(blank=True, verbose_name='Matn')),
                ('body_ru', models.TextField(blank=True, verbose_name='Matn (ru)')),
                ('image', models.ImageField(blank=True, upload_to='articles/', verbose_name='Rasm')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Chop etilgan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-published_at', '-id'],
            },
            bases=(pages.mixins.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=160, verbose_name='Sarlavha (ru)')),
                ('subtitle', models.CharField(blank=True, max_length=240, verbose_name='Matn')),
                ('subtitle_ru', models.CharField(blank=True, max_length=240, verbose_name='Matn (ru)')),
                ('image', models.ImageField(blank=True, upload_to='banners/', verbose_name='Rasm')),
                ('button_text', models.CharField(blank=True, max_length=60, verbose_name='Tugma matni')),
                ('button_text_ru', models.CharField(blank=True, max_length=60, verbose_name='Tugma matni (ru)')),
                ('button_url', models.CharField(blank=True, max_length=255, verbose_name='Tugma havolasi')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['sort_order', 'id'],
            },
            bases=(pages.mixins.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80, verbose_name='Shahar')),
                ('city_ru', models.CharField(blank=True, max_length=80, verbose_name='Shahar (ru)')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('address_ru', models.CharField(blank=True, max_length=255, verbose_name='Manzil (ru)')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('working_hours', models.CharField(blank=True, max_length=120, verbose_name='Ish vaqti')),
                ('working_hours_ru', models.CharField(blank=True, max_length=120, verbose_name='Ish vaqti (ru)')),
                ('map_url', models.URLField(blank=True, verbose_name='Xarita havolasi')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['sort_order', 'id'],
            },
            bases=(pages.mixins.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Masalan: jalyuzi-turlari', unique=True, verbose_name='Kalit')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (ru)')),
                ('body', models.TextField(verbose_name='Matn (HTML ruxsat etilgan)')),
                ('body_ru', models.TextField(blank=True, verbose_name='Matn (ru)')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='Bosh sahifada ko‘rsatish')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Kontent bloki',
                'verbose_name_plural': 'Kontent bloklari',
                'ordering': ['sort_order', 'id'],
            },
            bases=(pages.mixins.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Savol')),
                ('question_ru', models.CharField(blank=True, max_length=255, verbose_name='Savol (ru)')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('answer_ru', models.TextField(blank=True, verbose_name='Javob (ru)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Savol-javob',
                'verbose_name_plural': 'Savol-javoblar',
                'ordering': ['sort_order', 'id'],
            },
            bases=(pages.mixins.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Nomi')),
                ('name_ru', models.CharField(blank=True, max_length=140, verbose_name='Nomi (ru)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='🛠', max_length=8, verbose_name='Ikon (emoji)')),
                ('short_description', models.CharField(blank=True, max_length=240, verbose_name='Qisqa tavsif')),
                ('short_description_ru', models.CharField(blank=True, max_length=240, verbose_name='Qisqa tavsif (ru)')),
                ('description', models.TextField(blank=True, verbose_name='To‘liq tavsif')),
                ('description_ru', models.TextField(blank=True, verbose_name='To‘liq tavsif (ru)')),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='Rasm')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['sort_order', 'id'],
            },
            bases=(pages.mixins.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Sevara Design', max_length=80, verbose_name='Brend nomi')),
                ('tagline', models.CharField(blank=True, max_length=160, verbose_name='Shior')),
                ('tagline_ru', models.CharField(blank=True, max_length=160, verbose_name='Shior (ru)')),
                ('about_short', models.TextField(blank=True, verbose_name='Qisqacha ma’lumot')),
                ('about_short_ru', models.TextField(blank=True, verbose_name='Qisqacha ma’lumot (ru)')),
                ('about_full', models.TextField(blank=True, verbose_name='Biz haqimizda (to‘liq)')),
                ('about_full_ru', models.TextField(blank=True, verbose_name='Biz haqimizda (to‘liq, ru)')),
                ('phone_primary', models.CharField(default='+998 78 113 04 00', max_length=40, verbose_name='Asosiy telefon')),
                ('phone_secondary', models.CharField(blank=True, max_length=40, verbose_name='Qo‘shimcha telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(blank=True, max_length=120, verbose_name='Ish vaqti')),
                ('working_hours_ru', models.CharField(blank=True, max_length=120, verbose_name='Ish vaqti (ru)')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
            bases=(pages.mixins.TranslatableMixin, models.Model),
        ),
    ]
