# Generated by Django 5.2.17 on 2026-08-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_primary',
            field=models.CharField(default='+998 99 986 71 99', max_length=40, verbose_name='Asosiy telefon'),
        ),
    ]
