# Generated by Django 5.2.17 on 2026-08-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_delete_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='key',
            field=models.SlugField(help_text='Masalan: parda-turlari', unique=True, verbose_name='Kalit'),
        ),
    ]
