# Generated by Django 5.2.17 on 2026-08-14 08:37

import pages.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_contentblock_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nomi')),
                ('logo', models.ImageField(blank=True, upload_to='clients/', verbose_name='Logotip')),
                ('url', models.URLField(blank=True, verbose_name='Sayti')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120, verbose_name='Mijoz ismi')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='Kim (shahar yoki lavozim)')),
                ('role_ru', models.CharField(blank=True, max_length=120, verbose_name='Kim (ru)')),
                ('text', models.TextField(verbose_name='Sharh matni')),
                ('text_ru', models.TextField(blank=True, verbose_name='Sharh matni (ru)')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Baho (1–5)')),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Surat')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Mijoz fikri',
                'verbose_name_plural': 'Mijozlar fikri',
                'ordering': ['sort_order', 'id'],
            },
            bases=(pages.mixins.TranslatableMixin, models.Model),
        ),
    ]
