# Generated by Django 5.2.17 on 2026-08-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_client_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Manzil (ru)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_url',
            field=models.URLField(blank=True, verbose_name='Xarita havolasi'),
        ),
    ]
