# Generated by Django 5.2.17 on 2026-08-25 11:13

import pages.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_sitesettings_address_sitesettings_address_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (ru)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Turi')),
                ('category_ru', models.CharField(blank=True, max_length=100, verbose_name='Turi (ru)')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='Qisqacha tavsif')),
                ('excerpt_ru', models.CharField(blank=True, max_length=300, verbose_name='Qisqacha tavsif (ru)')),
                ('description', models.TextField(blank=True, verbose_name="To'liq tavsif")),
                ('description_ru', models.TextField(blank=True, verbose_name="To'liq tavsif (ru)")),
                ('image', models.ImageField(upload_to='works/', verbose_name='Asosiy rasm')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Ishim',
                'verbose_name_plural': 'Mening ishlarim',
                'ordering': ['-created_at', '-id'],
            },
            bases=(pages.mixins.TranslatableMixin, models.Model),
        ),
    ]
