# Generated by Django 5.2.17 on 2026-08-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['sort_order', '-created_at', '-id'], 'verbose_name': 'Ish', 'verbose_name_plural': 'Mening ishlarim'},
        ),
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(blank=True, help_text='Masalan: Zebra parda, Rimcha parda', max_length=100, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Qo‘shilgan sana'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, verbose_name='To‘liq tavsif'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='To‘liq tavsif (ru)'),
        ),
    ]
