# Generated by Django 5.2.17 on 2026-08-29 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Amal')),
                ('summary', models.CharField(max_length=255, verbose_name='Tavsif')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Yuborilgan maydonlar')),
                ('status', models.CharField(choices=[('done', 'Bajarildi'), ('failed', 'Xato')], default='done', max_length=10, verbose_name='Holat')),
                ('error', models.TextField(blank=True, verbose_name='Xato matni')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yozuv raqami')),
                ('object_url', models.CharField(blank=True, max_length=255, verbose_name='Yozuv manzili')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_actions', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Yordamchi amali',
                'verbose_name_plural': 'Yordamchi amallari',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
