# Generated by Django 5.2.17 on 2026-08-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_roles_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('support', 'Support (suhbatlar)'), ('manager', 'Menejer'), ('admin', 'Administrator')], default='manager', max_length=20, verbose_name='Rol'),
        ),
    ]
