# Generated by Django 5.2.17 on 2026-08-27 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Sessiya')),
                ('status', models.CharField(choices=[('bot', 'Bot javob bermoqda'), ('waiting_operator', 'Operator kutilmoqda'), ('with_operator', 'Operator ulangan'), ('closed', 'Yopilgan')], default='bot', max_length=20, verbose_name='Holat')),
                ('language', models.CharField(default='uz', max_length=5, verbose_name='Til')),
                ('visitor_name', models.CharField(blank=True, max_length=120, verbose_name='Mijoz ismi')),
                ('visitor_phone', models.CharField(blank=True, max_length=30, verbose_name='Mijoz telefoni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan')),
                ('last_message_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oxirgi xabar')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='Operator so‘ralgan')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Suhbat',
                'verbose_name_plural': 'Suhbatlar',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('visitor', 'Mijoz'), ('ai', 'Sun’iy intellekt'), ('operator', 'Operator'), ('system', 'Tizim')], max_length=20, verbose_name='Kim yozdi')),
                ('text', models.TextField(verbose_name='Matn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('seen_by_operator', models.BooleanField(default=False, verbose_name='Operator ko‘rdi')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.conversation', verbose_name='Suhbat')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['id'],
            },
        ),
    ]
