# Generated by Django 5.2.17 on 2026-08-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_lead_and_cart_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('callback', 'Qo‘ng‘iroqni so‘rash'), ('consultation', 'Bepul konsultatsiya'), ('discount', '10% chegirma'), ('measure', 'Bepul o‘lchov'), ('order', 'Buyurtma so‘rovi'), ('contact', 'Aloqa formasi'), ('popup', 'Bildirishnoma')], default='callback', max_length=20, verbose_name='Ariza turi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('termiz-shahri', 'Termiz shahri'), ('denov-shahri', 'Denov shahri'), ('angor', 'Angor tumani'), ('bandixon', 'Bandixon tumani'), ('boysun', 'Boysun tumani'), ('denov', 'Denov tumani'), ('jarqorgon', 'Jarqo‘rg‘on tumani'), ('muzrabot', 'Muzrabot tumani'), ('oltinsoy', 'Oltinsoy tumani'), ('qiziriq', 'Qiziriq tumani'), ('qumqorgon', 'Qumqo‘rg‘on tumani'), ('sariosiyo', 'Sariosiyo tumani'), ('sherobod', 'Sherobod tumani'), ('shorchi', 'Sho‘rchi tumani'), ('termiz', 'Termiz tumani'), ('uzun', 'Uzun tumani')], default='termiz-shahri', max_length=40, verbose_name='Tuman / shahar'),
        ),
    ]
